# Generated by Django 5.2.1 on 2025-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subreddit', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
